### PR TITLE
Delegate index system

### PR DESCRIPTION
**Pull request by theeblardo**
coldkey 5CezfqBQx7gy9YL69mepHDPHUC4unV1HYcCtYa5KdXEerBUN
hotkey 5D9wuLzoWSbucNx6NQRo7wdNfvW2poMy3NumSiggsEStPc9X

TAO ALMANACH

TAO ALMANACH is the validator of bittensor mod blardo and polkadot mod mister_cole, and we'd love your delegation!

okay, can't figure out the signature ... got this instead:
honestly i think this is the best way to prove it is blardo and mr_cole

(well, i tried ... blardo)

### CODE REVIEW

**Comment by mrseeker** [comment]
@theeblardo Have your tried running it on the same server as the validator, using "python3" instead of "python"?

**Comment by theeblardo** [comment]
yep.  i did using python 3 and the screenshot is the result.

blardo

(ps ... such a smoooooth brain.  this should be low priority for all
y'all.  i'd like to get on the list, but have to get back to my real life
for a while now)

**Comment by camfairchild** [comment]
@theeblardo Please open a new PR with a signature or a screenshot of an on-chain remark

**Comment by theeblardo** [comment]
what qualifies as an on-chain remark? would btcli overview be sufficient?

blardo

**Pull request closed without merging**
