### PR TITLE
add foundry digital validator

### PR DESCRIPTION
**Pull request by teast21**
add foundry digital validator

### CODE REVIEW

**Comment by teast21** [comment]
Validator signature: 8e645d5191330b07930a2fd68738cdee8f214224562b221bce6901998a0d4c2d54c61ab9b943ba160e970b4cacfca3a8bfc9f98ac990783944a08be396646f85

**Comment by unconst** [comment]
@teast21 Could you please submit the validator information output also

I'm placing the following and getting an error
Validator information: {"5HEo565WAy4Dbq3Sv271SAi7syBSofyfhhwRNjFNSM2gP9M2": {"name": "Foundry", "url": "https://foundrydigital.com", "description": "Foundry works to empower a decentralized infrastructure. We are protocol-agnostic and seek to support like-minded blockchain entrepreneurs who share our mission to advance the industry."}} 
Validator signature: 8e645d5191330b07930a2fd68738cdee8f214224562b221bce6901998a0d4c2d54c61ab9b943ba160e970b4cacfca3a8bfc9f98ac990783944a08be396646f85
5HEo565WAy4Dbq3Sv271SAi7syBSofyfhhwRNjFNSM2gP9M2
Verified False

**Comment by teast21** [comment]
Verified True
        Validator information: {"5HEo565WAy4Dbq3Sv271SAi7syBSofyfhhwRNjFNSM2gP9M2": {"name": "Foundry", "url": "https://foundrydigital.com", "description": "Foundry works to empower a decentralized infrastructure. We are protocol-agnostic and seek to support like-minded blockchain entrepreneurs who share our mission to advance the industry."}}
        Validator signature: b852f1648ab62befaaf684671808aa34d267cd616d9ffd7b3cf924ebc7c4ee3255344cfd017a80ca6b23b2852bcafa705c42d231053e06d999d53f31bd8ab288

**Comment by unconst** [comment]
Verified.

Validator information: {"5HEo565WAy4Dbq3Sv271SAi7syBSofyfhhwRNjFNSM2gP9M2": {"name": "Foundry", "url": "https://foundrydigital.com", "description": "Foundry works to empower a decentralized infrastructure. We are protocol-agnostic and seek to support like-minded blockchain entrepreneurs who share our mission to advance the industry."}}
Validator signature: b852f1648ab62befaaf684671808aa34d267cd616d9ffd7b3cf924ebc7c4ee3255344cfd017a80ca6b23b2852bcafa705c42d231053e06d999d53f31bd8ab288
5HEo565WAy4Dbq3Sv271SAi7syBSofyfhhwRNjFNSM2gP9M2
Verified True

**Pull request merged**
