### PR TITLE
Update delegates.json

### PR DESCRIPTION
**Pull request by wildcommunist**
Validator signature: b41db5092b7e6fde8eeab5133527a334f7b82498eaa8a1c6e59d474af64a0663ca334013a323dfa2c5213e97c8468ff3c868d3d64cb73fdab6a68e649e3d1187

### CODE REVIEW

**Comment by unconst** [comment]
Hi @wildcommunist could you submit the validator information message from the output as well. This way I can validate the signature.

**Comment by unconst** [comment]
Should look like this: https://github.com/opentensor/bittensor/pull/1163#issuecomment-1475436700

**Comment by wildcommunist** [comment]
@unconst 
```
        Verified True
        Validator information: {"5FFApaS75bv5pJHfAp2FVLBj9ZaXuFDjEypsaBNc1wCfe52v": {"name": "RoundTable21", "url": "https://roundtable21.com", "description": "RoundTable21 is an International, multi-disciplinary team of consultants and advisors partnering alongside leading blockchain startups to offer guidance, expertise, investment and hands-on assistance in every aspect of development."}}
        Validator signature: 107638b8edde8f918f7faa2cd1f91b454c13094ed5955d6a409f6e0662f8427075516273728a53923839a5428079151ea0844b5f755362364f04735463dff583
```

**Comment by unconst** [comment]
Validator information: {"5FFApaS75bv5pJHfAp2FVLBj9ZaXuFDjEypsaBNc1wCfe52v": {"name": "RoundTable21", "url": "https://roundtable21.com", "description": "RoundTable21 is an International, multi-disciplinary team of consultants and advisors partnering alongside leading blockchain startups to offer guidance, expertise, investment and hands-on assistance in every aspect of development."}}
Validator signature: 107638b8edde8f918f7faa2cd1f91b454c13094ed5955d6a409f6e0662f8427075516273728a53923839a5428079151ea0844b5f755362364f04735463dff583
5FFApaS75bv5pJHfAp2FVLBj9ZaXuFDjEypsaBNc1wCfe52v
Verified True

**Pull request merged**
