### PR TITLE
Adding gpt4_x_vicuna, OpenLLaMA and MPT_Chat

### PR DESCRIPTION
**Pull request by ViktorThink**
Adding three new model implementations for mining:
gpt4-x-vicuna by NousResearch - https://huggingface.co/NousResearch/gpt4-x-vicuna-13b
mpt-chat by Mosaicml- https://huggingface.co/mosaicml/mpt-7b-chat
open_llama  by OpenLM Research - https://huggingface.co/openlm-research/open_llama_7b_preview_200bt/tree/main

I've tested all models, and gpt4-x-vicuna and MPT_Chat works great.

OpenLLaMA though has only been trained for general text generation, and not on chat data, and thus tends to generate long repetetive answers until it hits the token limit. I'm working on a quick fix, but probably will work better when it is trained on a downstream task.

### CODE REVIEW

**Comment by ViktorThink** [comment]
Here are some example generations:

Gpt4_x_vicuna
```

Message: [{'role': 'system', 'content': 'After Hurricane Katrina in 2005, Beyonc_ and Rowland founded the Survivor Foundation to provide transitional housing for victims in the Houston area, to which Beyonc_ contributed an initial $250,000. The foundation has since expanded to work with other charities in the city, and also provided relief following Hurricane Ike three years later.'}, {'role': 'user', 'content': 'Can you provide more details about the education and mentoring programs for young people that the Survivor Foundation supports?'}]
Generation: Certainly! The Survivor Foundation is dedicated to providing education and mentoring programs for young people. Their education program focuses on providing access to quality education and resources to help young people succeed in school and beyond. The mentoring program pairs young people with caring adults who serve as positive role models and provide guidance and support. The Survivor Foundation also offers various workshops and events to empower young people and help them develop essential life skills.


Message: [{'role': 'user', 'content': "Unfortunately, as an AI language model, I do not have access to the most current information about the Survivor Foundation's programs. However, according to their website, the Survivor Foundation has provided support for education and mentoring programs for young people in the past. The foundation has partnered with organizations such as the Boys and Girls Club and the Knowles-Rowland Center for Youth to provide after-school and summer programs for children in underserved communities. These programs have included academic enrichment, leadership development, and career exploration. Additionally, the foundation has provided scholarships and financial assistance to students pursuing higher education.\n\n\nAsk a follow up question.\n"}]
Generation: Can you tell me more about the specific programs and initiatives that the Survivor Foundation has supported in terms of education and mentoring for young people?


Message: [{'role': 'user', 'content': 'Dog communication is about how dogs "speak" to each other, how they understand messages that humans send to them, and how humans can translate the ideas that dogs are trying to transmit.:xii These communication behaviors include eye gaze, facial expression, vocalization, body posture (including movements of bodies and limbs) and gustatory communication (scents, pheromones and taste). Humans communicate with dogs by using vocalization, hand signals and body posture.\n\n\nAsk a follow up question.\n'}]
Generation: What are some common misconceptions people have about how dogs communicate with each other and with humans?


Message: [{'role': 'system', 'content': 'Marien Ngouabi, who had participated in the coup, assumed the presidency on December 31, 1968. One year later, President Ngouabi proclaimed Congo Africa\'s first "people\'s republic", the People\'s Republic of the Congo, and announced the decision of the National Revolutionary Movement to change its name to the Congolese Labour Party (PCT). Ngouabi survived an attempted coup in 1972 but was assassinated on March 16, 1977. An 11-member Military Committee of the Party (CMP) was then named to head an interim government with Joachim Yhombi-Opango to serve as President of the Republic. Two years later, Yhombi-Opango was forced from power and Denis Sassou Nguesso become the new president.'}, {'role': 'user', 'content': 'What were the major accomplishments of Marien Ngouabi during his presidency?'}]
Generation: Marien Ngouabi was the President of the Republic of the Congo from 1969 until his assassination in 1977. During his presidency, he implemented a number of socialist and nationalist policies, aiming to bring about greater equality and economic development in the country. One of his major accomplishments was the nationalization of several key industries, including banking, mining, and agriculture. He also made efforts to expand education and healthcare access to more people in the country. However, his presidency was also marked by political unrest and violence, and his legacy remains a subject of debate in the Congo today.
```

Mpt_chat
```
Message: [{'role': 'system', 'content': 'In fact, there was an eighth province, the County of Drenthe, but this area was so poor it was exempt from paying federal taxes and as a consequence was denied representation in the States General. Each province was governed by the Provincial States, the main executive official (though not the official head of state) was a raadspensionaris. In times of war, the stadtholder, who commanded the army, would have more power than the raadspensionaris.'}, {'role': 'user', 'content': 'What were the duties and responsibilities of a stadtholder in the Netherlands during this time period?'}]

Generation: The stadtholder was the military and political leader of the Netherlands during the Dutch Golden Age. The stadtholder was the commander-in-chief of the army and had the power to appoint and dismiss the raadspensionaris, the main executive official of each province. The stadtholder also had the power to dissolve the States General, the unicameral legislature that represented the seven provinces. The stadtholder was also the official head of state, but this was a largely ceremonial role.

Message: [{'role': 'system', 'content': 'The iPod line can play several audio file formats including MP3, AAC/M4A, Protected AAC, AIFF, WAV, Audible audiobook, and Apple Lossless. The iPod photo introduced the ability to display JPEG, BMP, GIF, TIFF, and PNG image file formats. Fifth and sixth generation iPod Classics, as well as third generation iPod Nanos, can additionally play MPEG-4 (H.264/MPEG-4 AVC) and QuickTime video formats, with restrictions on video dimensions, encoding techniques and data-rates. Originally, iPod software only worked with Mac OS; iPod software for Microsoft Windows was launched with the second generation model. Unlike most other media players, Apple does not support Microsoft\'s WMA audio format_but a converter for WMA files without Digital Rights Management (DRM) is provided with the Windows version of iTunes. MIDI files also cannot be played, but can be converted to audio files using the "Advanced" menu in iTunes. Alternative open-source audio formats, such as Ogg Vorbis and FLAC, are not supported without installing custom firmware onto an iPod (e.g., Rockbox).'}, {'role': 'user', 'content': 'What is the maximum frame rate supported by these iPod models while playing videos?'}]

Generation: The maximum frame rate supported by the fifth and sixth generation iPod Classics, as well as third generation iPod Nanos, is 720p. The maximum frame rate supported by the first, second, and third generation iPod Touches is 720p or 1080p. The maximum frame rate supported by the fourth generation iPod Touches is 720p or 1080p. The maximum frame rate supported by the iPod nano (7th generation) is 720p. The maximum frame rate supported by the iPod touch (5th generation) is 720p or 1080p. The maximum frame rate supported by the iPod touch (6th generation) is 720p or 1080p. The maximum frame rate supported by the iPod touch (7th generation) is 720p or 1080p. The maximum frame rate supported by the iPhone is 720p or 1080p. The maximum frame rate supported by the iPad is 720p or 1080p. The maximum frame rate supported by the Apple TV is 720p or 1080p.

```

OPEN_LLAMA
```
Message: [{'role': 'system', 'content': 'This season also saw the launch of the American Idol Songwriter contest which allows fans to vote for the "coronation song". Thousands of recordings of original songs were submitted by songwriters, and 20 entries selected for the public vote. The winning song, "This Is My Now", was performed by both finalists during the finale and released by Sparks on May 24, 2007.'}, {'role': 'user', 'content': 'Were there any notable achievements or chart success for "This Is My Now"?'}]

Generation: Yes, the song was nominated for a Grammy Award for Best Pop Collaboration with Vocals.

Message: [{'role': 'system', 'content': 'The 2008 Summer Olympics torch relay was run from March 24 until August 8, 2008, prior to the 2008 Summer Olympics, with the theme of "one world, one dream". Plans for the relay were announced on April 26, 2007, in Beijing, China. The relay, also called by the organizers as the "Journey of Harmony", lasted 129 days and carried the torch 137,000 km (85,000 mi) _ the longest distance of any Olympic torch relay since the tradition was started ahead of the 1936 Summer Olympics.'}, {'role': 'user', 'content': 'What steps have been taken to address the lack of diversity in the relay team?'}]

Generation: The torch relay team is diverse.
```

**Comment by ViktorThink** [comment]
Anyone who can check/approve the PR? Maybe @ifrit98 ?

**Comment by ifrit98** [comment]
Will take a look at this later tonight or tomorrow at the latest.

**Comment by ifrit98** [comment]
@ViktorThink, loading gpt4_x_vicuna and mbt-7b-chat work just fine.

Small issue with open_llama REAMDE is incorrect. There are arguments you suggest for downloading the hf model do not exist in the `download_model_from_hf.py`

E.g.
Args suggested:
```bash
#Download model to local folder
python3 neurons/text/prompting/miners/open_llama/download_model_from_hf.py --model_name MODEL_NAME_ON_HF --target_folder TARGET_FOLDER_TO_DOWNLOAD_FROM  --local_folder LOCAL_FOLDER```
```

Code:
```python
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_name", default="openlm-research/open_llama_7b_preview_300bt", help="Hugging Face model name")
    parser.add_argument("--local_folder", default="open_llama_7b_preview_300bt_transformers_weights", help="Local folder to save the model files")

    args = parser.parse_args()
```

Can you please update this so users can download model correctly?  Will close after this and can get the model loaded/tested.

**Comment by ViktorThink** [comment]
Nice spotting @ifrit98

Now it's fixed and I tested that it works as expected.

**Comment by ifrit98** [comment]
Need to validate this and then will merge.

**Comment by ViktorThink** [comment]
@ifrit98 have you had time to test it yet?

**Comment by ifrit98** [comment]
1st error:
```
Traceback (most recent call last):
  File "/home/jason/.b/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/jason/.b/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/openlm-research/open_llama_7b_preview_300bt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "download_hf.py", line 43, in <module>
    main(args.model_name, args.target_folder, args.local_folder)
  File "download_hf.py", line 20, in main
    model_info = api.model_info(model_name)
  File "/home/jason/.b/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/jason/.b/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1604, in model_info
    hf_raise_for_status(r)
  File "/home/jason/.b/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6464d2a8-7bf827f13467ca635b27b22e)

Repository Not Found for url: https://huggingface.co/api/models/openlm-research/open_llama_7b_preview_300bt.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```

Seems the HF repo has changed, please change defaults accordingly.  

2nd error:
When I manually specified the correct model, nothing happens.
```
(~$ python download_model_from_hf.py 
All files downloaded. #instantly
```

But when I go look in the dir, nothing is there:
```
~/open_llama_7b_preview_400bt_transformers_weights$ ll
total 8
drwxrwxr-x  2 jason jason 4096 May 17 13:14 ./
drwxr-xr-x 34 jason jason 4096 May 17 13:14 ../
```

Please fix these errors before I can merge.

**Comment by ViktorThink** [comment]
Ah, seems like they released new checkpoints that already use the huggingface format, that means we don't even have to download the model, we can just specify the name when starting the miner, which is nice.

I think I should be able to update and verify that it works within one hour.

**Comment by ViktorThink** [comment]
I tested now with this model: openlm-research/open_llama_7b_400bt_preview

And it worked without issues. Thank you for your patience @ifrit98

**Review by ifrit98 — APPROVED** [review]
Beautiful.  Thanks @ViktorThink, all set to merge.

**Pull request merged**
