### PR TITLE
Bittensor init

### PR DESCRIPTION
**Pull request by unconst**
import bittensor as bt
bt.embed( "this is a sentence I want to embed" )

import bittensor as bt
bt.init( "wallet name", "hotkey name" )
bt.embed( "this is a sentence I want to embed", uid = 100)

### CODE REVIEW

**Review by robertalanm — COMMENTED** [review]
LGTM!

**Review by camfairchild — APPROVED** [review]
LGTM

**Comment by camfairchild** [comment]
@unconst make sure to add correct copyright notice year on new files

**Comment by Eugene-hu** [comment]
Changing the base branch from master to nobunaga

**Pull request closed without merging**
