### PR TITLE
changed local train and remote train descriptions

### PR DESCRIPTION
**Pull request by quac88**
local and remote train sometimes cause bugs if set to false. The default is already false, so an extra note is added to remind users to only use this flag when passing true

### CODE REVIEW

**Comment by camfairchild** [comment]
I think the description should be more like "Set this flag to enable [...]".

Good PR, though! Definitely needed.

**Comment by camfairchild** [comment]
Also, make sure to merge PRs into nobunaga instead of master

**Review by shibshib — APPROVED** [review]

**Review by unconst — APPROVED** [review]

**Comment by shibshib** [comment]
@quac88 I just noticed this is effectively trying to merge your repository to this repository :D 

We can't merge this since this is your personal repository. You need to do a git checkout on the opentensor foundation's repo, and then make a new branch with these change and push it up.

**Comment by camfairchild** [comment]
imo this should be merged into nobunaga first so it doesn't mess with our branching

**Pull request closed without merging**
