### PR TITLE
Part 4 for refactoring bittensor/subtensor.py

### LINKED ISSUE #1908: bittensor.subtensor module refactoring
### Is your feature request related to a problem? Please describe.

As a part of https://github.com/opentensor/bittensor/issues/1882

### Describe the solution you'd like

- [x] Style refactoring
- [x] Сode refactoring

- [ ] ~~Implement the ability to use functions in an asynchronous implementation.~~ Decided to do this in different PR

### PR DESCRIPTION
**Pull request by basfroman**
Since the refactoring of this module would turn into a large project, it was decided to divide it into several stages.

This is part 4: current part affects everything up to the subtensor().tx_rate_limit() method.
Test coverage improved.

Part 1 https://github.com/opentensor/bittensor/pull/1911
Part 2 https://github.com/opentensor/bittensor/pull/1913
Part 3 https://github.com/opentensor/bittensor/pull/1923

### CODE REVIEW

**Comment by opendansor** [comment]
there are a few 
`Args: (Optional[int], optional):`

But other than that, LGTM.

**Comment by basfroman** [comment]
> there are a few `Args: (Optional[int], optional):`
> 
> But other than that, LGTM.

This is correct docstring. First `Optional[int]` means the type of the argument. The second one `optional` means that you you may not provide this argument and in this case it have to be equal to default value.

For the comparison another example:
```python
    def unstake_multiple(
        self,
        wallet: "bittensor.wallet",
        hotkey_ss58s: List[str],
        amounts: Optional[List[Union["Balance", float]]] = None,
        wait_for_inclusion: bool = True,
        wait_for_finalization: bool = False,
        prompt: bool = False,
    ) -> bool:
        """ 
        ...
        Args:
            amounts (Optional[List[Union[Balance, float]]], optional): The am ...
        ...
        """
```
It was confusing me too then I realized what does it mean.

**Review by opendansor — APPROVED** [review]

**Review by ibraheem-abe — APPROVED** [review]
Overall LGTM 
I personally prefer the left-hand style more due to its structure 😄  but that's just me
image

**Comment by basfroman** [comment]
> Overall LGTM I personally prefer the left-hand style more due to its structure 😄 but that's just me image

the essence of my approach is that first we check edge cases and undesirable cases, and then happy)

**Pull request merged**
