### PR TITLE
Fix Docker Build and Docker-Compose

### PR DESCRIPTION
**Pull request by rmaronn**
This PR:

### **- Irons out the Python version inconsistency between the install scripts and the Dockerfile**

Right now, the Docker image builds with Python3.7, but the `install.sh` script per the install instructions installs Python3.8. This is because Python3 is installed in the install script, but we specifically point out 3.7 in the Dockerfile. This causes the docker container to not be compatible with the new keccak update, breaking it.

### **- Fixes the Docker Compose spec to have the command correctly route and find the Bittensor Python library**

Previously, we were not specifying the path to the Bittensor Python library. By specifying the `PYTHONPATH` environment variable, we are able to tell it where to go to find it.

### CODE REVIEW

**Comment by ghost** [comment]
Allows users to use docker without custom editing docker-compose.  Very useful.

**Review by shibshib — APPROVED** [review]

**Comment by rmaronn** [comment]
Please note - the build fails now due to NVIDIA rotating their public keys and not updating their corresponding Docker images. See here: https://forums.developer.nvidia.com/t/invalid-public-key-for-cuda-apt-repository/212901

**Comment by camfairchild** [comment]
> Please note - the build fails now due to NVIDIA rotating their public keys and not updating their corresponding Docker images. See here: https://forums.developer.nvidia.com/t/invalid-public-key-for-cuda-apt-repository/212901

The workaround for this is to modify your Dockerfile with the following under line 14  up to the `apt-get update` on line 17  
        
        # Nvidia Key Rotation
        ## https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772
        ## Remove old Nvidia GPG key and source list
        ## Prevents apt from failing to find the key
        RUN rm /etc/apt/sources.list.d/cuda.list \
            && rm /etc/apt/sources.list.d/nvidia-ml.list 
        RUN apt-key del 7fa2af80
        
        # apt update and Install dependencies
        RUN apt-get update && \
            apt-get install --no-install-recommends --no-install-suggests apt-utils curl git \
	        cmake build-essential unzip python3-pip wget iproute2 software-properties-common
        
        # Nvidia Key Rotation
        ## https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772
        ## Add new Nvidia GPG key
        RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
        RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
        RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
        RUN dpkg -i cuda-keyring_1.0-1_all.deb
        
        RUN add-apt-repository ppa:deadsnakes/ppa
        RUN apt-get update && apt-get upgrade -y

**Comment by rmaronn** [comment]
> camfairchild

Thank you for the info! I had tried something similar on a testing branch but there was some other issue. I will implement this.

**Comment by rmaronn** [comment]
Should be all set!

**Review by shibshib — APPROVED** [review]

**Comment by rmaronn** [comment]
rebase to https://github.com/opentensor/bittensor/pull/772

**Pull request closed without merging**
