### PR TITLE
Update delegates.json

### PR DESCRIPTION
**Pull request by piotrekraw**
This commit purpose is to add a TaoPolishNode to the validators list

### CODE REVIEW

**Comment by unconst** [comment]
Hi @piotrekraw 

We need you to generate a signature for this information to verify your hotkey.
Please run the following code with your mnemonic and information to generate a signature we can validate.

```python
import json
import bittensor
mnemonic = input("Hotkey Mnemonic: ")
descriptive_name = input("Validator descriptive name (i.e. Opentensor Foundation): ")
url = input("Validator url (i.e. www.opentensor.org ): ")
description = input("Validator description ( i.e. build, maintain and advance Bittensor): ")
keypair = bittensor.Keypair.create_from_mnemonic("surround decrease mad utility opinion shoot magic worth ladder source say provide")
dictionary = {}
dictionary[ keypair.ss58_address ] = {
    'name': descriptive_name,
    'url': url,
    'description': description,
}
message = json.dumps( dictionary )
signature = keypair.sign( data = message )
print('\n\n\tVerified', bittensor.Keypair(ss58_address=keypair.ss58_address).verify( data = message, signature = signature) )
print (
    "\tValidator information: {}\n".format(message),
    "\tValidator signature: {}\n\n".format(signature.hex()),
)
```

**Comment by unconst** [comment]
Hi @piotrekraw can you please submit a signature for this PR generated from the following script:

https://gist.githubusercontent.com/unconst/6965a01bad729eec375ac6a97734c0ae/raw/8dd12a63083f4fd5a78ec92cf43851b244ddde12/Generating%2520a%2520Signature%2520for%2520your%2520validator%2520information

**Comment by piotrekraw** [comment]
> Hi @piotrekraw can you please submit a signature for this PR generated from the following script:
> 
> https://gist.githubusercontent.com/unconst/6965a01bad729eec375ac6a97734c0ae/raw/8dd12a63083f4fd5a78ec92cf43851b244ddde12/Generating%2520a%2520Signature%2520for%2520your%2520validator%2520information

sure 
	Verified True
	Validator information: {"5H6BgKkAr2Anmm9Xw5BVDE4VaQmFEVMkJUHeT7Gki4J7yF4x": {"name": "TaoPolishNode", "url": "https://taonode.io", "description": "This node is a collective effort of the polish community. We are engaged in evangelizing the project, educating and sharing the knowledge."}}
 	Validator signature: 1ca20d4e99a48f400dd9cd4aeca8447da6ab1979e480a1dafddfc52e45e215177c7cdde85f5d042d59a5b1169981afa8d1ae28328e2fc5ce57c3d748c8d09d81

**Comment by unconst** [comment]
Verified

**Review by unconst — APPROVED** [review]

**Comment by unconst** [comment]
Merged.

**Pull request merged**
