### PR TITLE
Update delegates.json

### PR DESCRIPTION
**Pull request by mtbua88**

### CODE REVIEW

**Comment by camfairchild** [comment]
Hi, please include a signature from your hotkey using this script https://gist.github.com/unconst/6965a01bad729eec375ac6a97734c0ae/

**Comment by mtbua88** [comment]
Will do, thank you

**Comment by mtbua88** [comment]
I apologize, I am not familiar with github, and I think I am making a
bigger mess than I had before.

**Comment by camfairchild** [comment]
Hi again @mtbua88, please check out https://github.com/opentensor/bittensor-delegates and make a PR there. It's more straightforward and we're migrating to that repo for delegates.json

**Pull request closed without merging**
