### PR TITLE
Add New Miners: Stable LM & Chat GLM

### PR DESCRIPTION
**Pull request by KMFODA**
As per private discord conversation with @unconst adding [Chat GLM](https://huggingface.co/THUDM/chatglm-6b) and [stable_lm](https://huggingface.co/stabilityai/stablelm-tuned-alpha-7b) miner support to the text_prompting network.

### CODE REVIEW

**Comment by ViktorThink** [comment]
Hi, I made an implementation for Pythia from HF, so I think you can likely copy most of the code for Chat GLM:
https://github.com/ViktorThink/bittensor/tree/text_prompting_vicuna/neurons/text/prompting/miners/pythia

**Comment by KMFODA** [comment]
Hi @ViktorThink yes I saw its a very helpful guide. Thank you! I think I'm almost there with this PR just need to test on the main net.

**Comment by ifrit98** [comment]
Crap, spoke to soon.  Reopened

**Comment by ifrit98** [comment]
Is this tested against latest master @KMFODA ?

Edit: Tested myself. All set.

**Comment by ifrit98** [comment]
So we already have the StablilityAI miner here: https://github.com/opentensor/bittensor/tree/master/neurons/text/prompting/miners/stabilityai

Closing. Please reopen to merge into release/5.1.0 with only Chat GLM.

**Comment by KMFODA** [comment]
Hey @ifrit98 apologies I was on leave this past week. Noted, I'll create a new pr for the Chat GLM miner. In terms of test, are there specific tests that need to be run before opening a PR for review?

**Pull request closed without merging**
