### PR TITLE
Add Owl Ventures Validator

### PR DESCRIPTION
**Pull request by igoraxz**
Verified True
	Validator information: {"5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp": {"name": "Owl Ventures 2", "url": "https://owlventures.co.uk", "description": "Owl Ventures Tao Validator 2"}}
 	Validator signature: c807eea902fb786cba8ef768a3ec025d735e3a547d034f82779bdbdcda73cd0fb27b784db9a88d08bb6d4cde3e95fc1257486d86c37b38f309ebb53b7c145b89

### CODE REVIEW

**Comment by camfairchild** [comment]
Hi, the signature is wrong for that data

**Comment by camfairchild** [comment]
I can reopen when you ammend

**Comment by igoraxz** [comment]
@camfairchild Here is updated signature, thanks! 

Verified True
	Validator information: {"5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp": {"name": "Owl Ventures", "url": "https://owlventures.co.uk", "description": "Owl Ventures Bittensor Validator"}}
 	Validator signature: 04e39ff19af7ee5a75e58c9e1a71b9f54a66d1d168a99532a859f129b68ba24a5b6a56eecae7790291859c82dbf0ec32eb18a069b6d9dabe1ef0339c0d189483

**Comment by unconst** [comment]
Still getting false on this

Validator information:  {"5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp": {"name": "Owl Ventures", "url": "https://owlventures.co.uk", "description": "Owl Ventures Bittensor Validator"}}
Validator signature: 04e39ff19af7ee5a75e58c9e1a71b9f54a66d1d168a99532a859f129b68ba24a5b6a56eecae7790291859c82dbf0ec32eb18a069b6d9dabe1ef0339c0d189483
5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp
Verified False

**Comment by unconst** [comment]
Nvm it works


Validator information: {"5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp": {"name": "Owl Ventures", "url": "https://owlventures.co.uk", "description": "Owl Ventures Bittensor Validator"}}
Validator signature: 04e39ff19af7ee5a75e58c9e1a71b9f54a66d1d168a99532a859f129b68ba24a5b6a56eecae7790291859c82dbf0ec32eb18a069b6d9dabe1ef0339c0d189483
5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp
Verified True

**Review by unconst — APPROVED** [review]

**Pull request merged**
