### PR TITLE
Update delegates.json

### PR DESCRIPTION
**Pull request by TAOVali**
Verified True
        Validator information: {"5EhvL1FVkQPpMjZX4MAADcW42i3xPSF1KiCpuaxTYVr28sux": {"name": "TAO-Validator.com", "url": "www.tao-validator.com", "description": "Maximize your return when staking with TAO-Validator.com. TAO-Validator.com is a highly secure validator that aims to become one of the top contributing entities to Bittensor"}}
        Validator signature: 368a852fc3eee7d29973a60ca77d883a68927e63e57dacf6739ef942a9789c12b3930229c87993b5190605bb1c622365f3e616bb18d850b01d1e785bf364278e

### CODE REVIEW

**Comment by camfairchild** [comment]
Closed as already completed

**Comment by TAOVali** [comment]
Dear Cameron,

Regarding PR 1217 and PR 1229, I just saw you closed it with comment “Closed as already completed”
However, our details are not visible in the CLI, see visual below, the purple line is us. Please let me know how we are going to get our details on there, thank you
Schermafbeelding 2023-03-24 143756

**Comment by camfairchild** [comment]
> Dear Cameron,
> 
> Regarding PR 1217 and PR 1229, I just saw you closed it with comment “Closed as already completed”
> However, our details are not visible in the CLI, see visual below, the purple line is us. Please let me know how we are going to get our details on there, thank you
> Schermafbeelding 2023-03-24 143756
> 

Hi, you need to properly update your client. I can assist with this if you need help.

**Comment by TAOVali** [comment]
ah ok, yes please, could you let me know the inputs? thanks

**Comment by camfairchild** [comment]
> ah ok, yes please, could you let me know the inputs? thanks  

Enter the bittensor repo directory  
`cd ~/.bittensor/bittensor`  
Make sure you are on the right branch
`git checkout master`  
Pull the latest changes
`git pull`  
Update the installation, if needed
`pip install -e .`  

Then try the command again 
`btcli list_delegates`

If you get an error on any of the steps, please let me know

**Comment by TAOVali** [comment]
fantastic Cameron. it worked, thanks for all your help

**Pull request closed without merging**
