### PR TITLE
Update delegates.json

### PR DESCRIPTION
**Pull request by arguad**
Adding in our validator.

### CODE REVIEW

**Comment by arguad** [comment]
Let me know if this is going to be processed, or if i should resubmit.

**Comment by camfairchild** [comment]
> Let me know if this is going to be processed, or if i should resubmit.

You need to generate a signature so we can verify the information, using this script:
https://gist.github.com/unconst/6965a01bad729eec375ac6a97734c0ae/

**Comment by camfairchild** [comment]
I can re-open this when you add the signature

**Comment by arguad** [comment]
> I can re-open this when you add the signature

In the script I should enter the **secretPhrase** correct? (Not **secretSeed**) ?

**Comment by arguad** [comment]
I used the seedPhrase. Quotes were tripping me up.

Validator signature: d8c2efb836e7a311cd15a9567487314b1f2c3bb5e8fa71d9b7b28f887360220e25bd1c14ff7627098b084730d878c77a479555d8a7071c5634e8209e0395588a

**Comment by camfairchild** [comment]
> I used the seedPhrase. Quotes were tripping me up.
> 
> Validator signature: d8c2efb836e7a311cd15a9567487314b1f2c3bb5e8fa71d9b7b28f887360220e25bd1c14ff7627098b084730d878c77a479555d8a7071c5634e8209e0395588a

Hi, this sig is not passing the verification. Please double-check the text entered is the same

**Comment by camfairchild** [comment]
Closed for #1218

**Pull request closed without merging**
