### PR TITLE
dont sync metagraph on neuron init

### PR DESCRIPTION
**Pull request by camfairchild**
This fixes errors that require the subtensor config to be passed on the CLI.

### CODE REVIEW

**Review by ifrit98 — APPROVED** [review]
Great catch!

Will port this over to `openminers` also.

**Review by p-ferreira — APPROVED** [review]
LGTM although I'm not sure if I understood the implication on the validator.
So we want to sync the metagraph with `self.subtensor`?

The current implementation on openvalidators syncs like
` self.metagraph.sync()`. I see in the metagraph code that `lite` is set to true by default, but the `subtensor` is initially empty and later filled with `bt.subtensor`. 

Should we replicate this approach to the `openvalidators` as well?

**Comment by ifrit98** [comment]
> Should we replicate this approach to the `openvalidators` as well?

I believe we should, as (soon-ish) `_neuron` will be removed from `bittensor` proper with the next release following `5.2.1`.

**Comment by ifrit98** [comment]
See https://github.com/opentensor/bittensor/pull/1426

**Comment by camfairchild** [comment]
> LGTM although I'm not sure if I understood the implication on the validator.
> So we want to sync the metagraph with `self.subtensor`?
> 
> The current implementation on openvalidators syncs like
> ` self.metagraph.sync()`. I see in the metagraph code that `lite` is set to true by default, but the `subtensor` is initially empty and later filled with `bt.subtensor`. 

The config for the subtensor, including any chain endpoint, only gets passed to `self.subtensor`

We also need that when syncing the metagraph, so we have to pass that in somehow, meaning we should sync using it and disable the auto-sync when it initializes the object (because it has no config param)

**Pull request merged**
