### PR TITLE
[BIT-594] Decrease validator moving average window

### PR DESCRIPTION
**Pull request by opentaco**
### [BIT-594] Decrease validator moving average window

Decrease validator moving average window from 20 (alpha=0.05) to 10 (alpha=0.1) steps. This parameter could probably eventually be set to alpha=0.2.

The current 20-step window means that a server model change will take 20 steps * ~250 blocks/epoch * 12 sec = approx. 17 hours to reach full score in the validator neuron stats, because of the moving average slowly weighing in new model performance. 17 hours is probably too long, and it is also likely affecting registration immunity.

[BIT-594]: https://opentensor.atlassian.net/browse/BIT-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Eugene-hu — APPROVED** [review]
I agree, currently it takes too long

**Review by isabella618033 — APPROVED** [review]
LGTM

Question tho, have we also considered changing blocks/epoch? Do we still need that to be as high as 250 * 12 sec = 50 mins?

If we push it to topk = 100, that means we need 4096 / 100 (topk) * 15 sec = 10 mins to sample through all 4096 peers. And 250 blocks/epoch means that we can sample through the network 5 times in an epoch.
And 20 steps means that we can sample the network 5*20 = 100 times before setting weight. (If we push topk from 20 -> 100)

**Comment by opentaco** [comment]
> LGTM
> 
> Question tho, have we also considered changing blocks/epoch? Do we still need that to be as high as 250 * 12 sec = 50 mins?
> 
> If we push it to topk = 100, that means we need 4096 / 100 (topk) * 15 sec = 10 mins to sample through all 4096 peers. And 250 blocks/epoch means that we can sample through the network 5 times in an epoch. And 20 steps means that we can sample the network 5*20 = 100 times before setting weight. (If we push topk from 20 -> 100)

Increasing `topk` and decreasing blocks/epoch should come later to speed up network cycling time, although it may likely have the effect of increasing server load, which will require more server memory/resources, so we'd need to gradually phase in larger `topk`.

**Comment by unconst** [comment]
Is this ready to merge?

**Review by unconst — APPROVED** [review]

**Pull request merged**
