### PR TITLE
Subnets/more info

### PR DESCRIPTION
**Pull request by ifrit98**
* Adds subcommands to bittensor (Much needed!)

### CODE REVIEW

**Comment by ifrit98** [comment]
https://github.com/opentensor/bittensor/blob/f1df71ec6bc3c88882a6a3721d9504cc7b57e203/tests/integration_tests/test_cli.py#L2123

When testing with `tests/integration_tests/test_cli.py`:
`FAILED tests/integration_tests/test_cli.py::TestCLIWithNetworkUsingArgs::test_delegate - OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.`

It's asking for wallet from the command line.

**Comment by ifrit98** [comment]
image

Seems like we're exiting erroneously? Think the `check_config` is the culprit but not sure if its the source or a downstream problem:

```python

    @staticmethod
    def check_config(config: "bittensor.config"):
        """
        Checks if the essential configuration exists under different command
    
        Args:
            config (bittensor.config): The configuration settings for the CLI.
        """
        # Check if command exists, if so, run the corresponding check_config.
        # If command doesn't exist, inform user and exit the program.
        if config.command in COMMANDS:
            command = config.command
            command_data = COMMANDS[command]
    
            if isinstance(command_data, dict):
                if config["subcommand"] == None:
                    # This probably isn't the best solution, refactor
                    for action in config["__parser"]._subparsers._actions:
                        if action.dest == "command" and action.choices[command]:
                            action.choices[command].print_help()
>                           sys.exit()
E                           SystemExit

bittensor/cli.py:226: SystemExit
```

**Comment by Rubberbandits** [comment]
> image
> Seems like we're exiting erroneously? Think the `check_config` is the culprit but not sure if its the source or a downstream problem:
> 
> ```python
>     @staticmethod
>     def check_config(config: "bittensor.config"):
>         """
>         Checks if the essential configuration exists under different command
>     
>         Args:
>             config (bittensor.config): The configuration settings for the CLI.
>         """
>         # Check if command exists, if so, run the corresponding check_config.
>         # If command doesn't exist, inform user and exit the program.
>         if config.command in COMMANDS:
>             command = config.command
>             command_data = COMMANDS[command]
>     
>             if isinstance(command_data, dict):
>                 if config["subcommand"] == None:
>                     # This probably isn't the best solution, refactor
>                     for action in config["__parser"]._subparsers._actions:
>                         if action.dest == "command" and action.choices[command]:
>                             action.choices[command].print_help()
> >                           sys.exit()
> E                           SystemExit
> 
> bittensor/cli.py:226: SystemExit
> ```

The CLI exits in Revolution in the same manner, when printing main argparser help.

**Comment by ifrit98** [comment]
> The CLI exits in Revolution in the same manner, when printing main argparser help.

Ahh, probably the test being flaky then.

**Pull request merged**
