### PR TITLE
Update delegates.json

### PR DESCRIPTION
**Pull request by TAOVali**
"5EhvL1FVkQPpMjZX4MAADcW42i3xPSF1KiCpuaxTYVr28sux": {
        "name": "TAO-Validator.com", 
        "url": "www.tao-validator.com", 
        "description": "TAO-Validator.com is a highly secure validator on the Bittensor Network. Maximize your return when staking with TAO-Validator.com"

### CODE REVIEW

**Comment by TAOVali** [comment]
Hi, could you please review? I changed APY and used what other validators are using. Please let me know if this is alright, I would like to have our name up their asap. thank you

**Comment by camfairchild** [comment]
> Hi, could you please review? I changed APY and used what other validators are using. Please let me know if this is alright, I would like to have our name up their asap. thank you

This seems alright to @unconst ? 
Please add a signature to this PR using the script: https://gist.github.com/unconst/6965a01bad729eec375ac6a97734c0ae/

**Comment by TAOVali** [comment]
Thanks Cameron, do I need to do the following: “Please add a signature to this PR using the script: https://gist.github.com/unconst/6965a01bad729eec375ac6a97734c0ae/ “?
If yes, how can I do this (I’m quite the noob with this stuff). Thanks

**Comment by TAOVali** [comment]
Guys, can we please speed this up, seems other pull requests in delegates.json have been approved but ours is not for 2 days. thanks!

**Comment by TAOVali** [comment]
Guys, can we please speed this up, seems other pull requests in delegates.json have been approved but ours is not for 2 days. thanks!

**Pull request closed without merging**
